# Site Build Settings

# jekyll-paginate configuration
paginate:            10

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag, jemoji]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Alexis Crozier"
description:	       "Developer Ruby on Rails Hotwire and Photographer."
author:                "Alexis Crozier"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
